Model:
  type: SISSA_RNN
  name: SISSA-R-A

Params:
  # Hidden size of the RNN.
  hidden_size: 128
  # Whether to use attention mechanism.
  attention: true
  # Number of packets in a window.
  # [AUTO-UPDATE] Sync with [basic.yml][Preprocessor.window_height] (sissautils.py, `update_model_config()`)
  n_pack: 64
  # Dimension of a single packet.
  # [AUTO-UPDATE] Sync with [basic.yml][Preprocessor.window_width] (sissautils.py, `update_model_config()`)
  pack_dim: 25
  # Number of classes to classify.
  # [AUTO-UPDATE] Sync with [basic.yml][Preprocessor.n_classes] (sissautils.py, `update_model_config()`)
  n_classes: 7

Train:
  # Directory to store weights
  weights_dir: results/weights
  # Directory to store train-acc, val-acc, train-loss... for each epoch
  train_log_dir: results/train_log
  device: cuda
  batch_size: 256
  epochs: 400
  lr: 0.00001
  weight_decay: 0.0001
  n_workers: 4
  pin_memory: false
  # Directory that contains train data and labels.
  # [AUTO-UPDATE] Sync with [basic.yml][Data.train_dir] (sissautils.py, `update_model_config()`)
  train_dir: data/train
  # Directory that contains validation data and labels.
  # [AUTO-UPDATE] Sync with [basic.yml][Data.val_dir] (sissautils.py, `update_model_config()`)
  val_dir: data/val

Test:
  # Directory that contains test data and labels.
  test_dir: data/val
  # Path to weights.
  weights_path: results/weights/SISSA-R-A/e-380_train-acc-0.966_val-acc-0.804.pt
  # Dir to save test results.
  out_dir: results/test_result
  # Device to use.
  device: cuda
  # Batch size.
  batch_size: 1
  # Number of workers.
  n_workers: 1
  # Whether to pin memory.
  pin_memory: false
  weight_path: results/weights/SISSA-R-A_w64/e-145_train-acc-0.892_val-acc-0.801.pt
